#server.port=8081
##spring.application.name=nacos-provider
##spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
##management.endpoints.web.exposure.include=*

server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        #nginx的1111端口集群配置
        server-addr: 192.168.31.196:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
