server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
  instance:
    instance-id: orderService80
    prefer-ip-address: true
#设置 feign 客户端超时时间(OpenFeigen 默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于正常情况下，两端连接所用的时间
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取到的时间所用的时间
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug