server:
  port: 80


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: cloud-provider-hystrix-order

#ribbon:
#  #指的是建立连接所用的时间，适用于正常情况下，两端连接所用的时间
#  ReadTimeout:  15000
#  #指的是建立连接后从服务器读取到的时间所用的时间
#  ConnectTimeout: 15000

#如果处理自身的容错就开启。开启方式与生产端不一样
feign:
  hystrix:
    enabled: true

logging:
  level:
    com.atguigu.springcloud.service.PaymentHystrixService: debug
